DROP DATABASE IF EXISTS POWERBI_DB

//CREATE AGRICULTURE DATABASE
CREATE DATABASE POWERBI_DB

//CREATE ITS RESPECTIVE SCHEMA
CREATE SCHEMA POWERBI_DATA

//CREATE THE TABLE
DROP TABLE IF EXISTS PBI_Dataset
CREATE TABLE PBI_Dataset(
    Year text,
    Location text,
    Area int,
    Rainfall decimal,
    Temperature decimal,
    Soiltype text,
    Irrigation text,
    Yields decimal,
    Humidity decimal,
    Crops text,
    Price int,
    Season text
);

SELECT * FROM PBI_DATASET

//CREATE A STAGE TO CONNECT TO POWER BI DESKTOP
DROP STAGE IF EXISTS pbi_stage
CREATE STAGE PowerBI_DB.PowerBI_DATA.pbi_stage
URL = 's3://powerbi-project-bkt'
storage_integration = PBI_INTEGRATION

//DESCRIBE THE INTEGRATION AND STAGE
DESC INTEGRATION PBI_INTEGRATION
DESC STAGE pbi_stage

//COPY THE DATABASE FROM S3 BUCKET TO POWER BI DATASET
COPY INTO PBI_DATASET 
FROM @pbi_stage
file_format = (type=csv field_delimiter=',' skip_header=1 )
on_error = 'continue'

//UPDATE THE DATA (INCREASE RAINFALL BY 10%)
UPDATE PBI_DATASET
SET RAINFALL = 1.1*RAINFALL

//DECREASE AREA BY 10%
UPDATE PBI_DATASET
SET AREA = 0.9*AREA

//CREATE NEW COLUMS AS YEARGROUP
//WHERE 2004-2009 = G1
//2010 - 2015 = G2
//2016 - 2019 = G3
ALTER TABLE PBI_DATASET
ADD YEARGROUP string;

//SELECT * FROM pbi_dataset
UPDATE PBI_DATASET
SET YEARGROUP = 'G1'
WHERE YEAR IN ('2004','2005','2006','2007','2008','2009')

UPDATE PBI_DATASET
SET YEARGROUP = 'G2'
WHERE YEAR IN ('2010','2011','2012','2013','2014','2015')

UPDATE PBI_DATASET
SET YEARGROUP = 'G3'
WHERE YEAR IN ('2016','2017','2018','2019')

//CREATE ANOTHER COLUMN NAMED RAINFALL GROUP
//WHERE RAINFALL <255 : VERY LOW
//RAINFALL 256 - 1200 : lOW
//RAINFALL 1201 - 2800 : MEDUIUM
//RAINFALL 2801 < : HIGH

ALTER TABLE PBI_DATASET
ADD RAINFALLGROUP string

UPDATE PBI_DATASET
SET RAINFALLGROUP = 'Very Low'
WHERE RAINFALL < 255

UPDATE PBI_DATASET
SET RAINFALLGROUP = 'Low'
WHERE RAINFALL BETWEEN 256 AND 1200

UPDATE PBI_DATASET
SET RAINFALLGROUP = 'Medium'
WHERE RAINFALL BETWEEN 1201 AND 2800

UPDATE PBI_DATASET
SET RAINFALLGROUP = 'High'
WHERE RAINFALL > 2801