//CREATE A STORAGE INTEGRATION FOR CONNECTING TO AMAZON S3 BUCKET

CREATE OR REPLACE STORAGE INTEGRATION PBI_INTEGRATION
TYPE = EXTERNAL_STAGE
STORAGE_PROVIDER = 'S3'
ENABLED = TRUE
STORAGE_AWS_ROLE_ARN = 'arn:aws:iam::885457519171:role/powerbi-role'
STORAGE_ALLOWED_LOCATIONS = ('s3://powerbi-project-bkt/')
COMMENT = 'Optional Comment'

//DESCRIBE THE INTEGRATION
DESC INTEGRATION PBI_INTEGRATION

